name: CTests

# TODO add cache (https://github.com/actions/cache) to cache gtest deps

on: [push, workflow_dispatch]

jobs:
  test-gtest-linux:
    runs-on: [self-hosted, linux]

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: CXX=clang++-19 CC=clang-19 cmake -S ${{github.workspace}}/ -B ${{runner.workspace}}/build -DCLANG_TIDY_NAME=clang-tidy-19

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . -j$(nproc)

      - name: Test
        working-directory: ${{runner.workspace}}/build
        run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test_results_xml
          path: ${{runner.workspace}}/build/tests/test-results/**/*.xml
  test-gtest-windows:
    runs-on: [self-hosted, windows]

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S ${{github.workspace}}\ -B ${{runner.workspace}}\build -G "Ninja"

      - name: Build
        working-directory: ${{runner.workspace}}\build
        run: cmake --build . -j"$env:NUMBER_OF_PROCESSORS"

      - name: Test
        working-directory: ${{runner.workspace}}\build
        run: $env:GTEST_OUTPUT="xml:test-results\"; $env:GTEST_COLOR="1"; ctest -V

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test_results_xml
          path: ${{runner.workspace}}\build\tests\test-results\**\*.xml
